### ISSUE TITLE
If changed the default rest port to another

### ISSUE THREAD

**Issue by Luyang2902** [js-on/PyQDB#2]
If changed the default rest port 9000  to another ,for example 8000, how to config the PyQDB?

**Comment by simplylu** [comment]
You can overwrite the base URL for the QuestDB class like this:
```py
db = QuestDB(base_url="http://127.0.0.1:8000")
```
Port 9000 on localhost is just the default value, as you can see from the docstring belonging to the QuestDB class.
```py
class QuestDB:
    def __init__(self, base_url: str = "http://127.0.0.1:9000"):
        """Init QuestDB Class
        Args:
            base_url (str, optional): API URL for QuestDB. Defaults to "http://127.0.0.1:9000".
        """
```

**Comment by Luyang2902** [comment]
thanks
